version: '3.8'
services:
  web:
    container_name: tagged_images_manager_service_local_web_container
    build: .
    image: tagged_images_manager_service_local_web
    command: >
      sh -c "./scripts/wait-for-postgres.sh &&
             python3 -m manage makemigrations &&
             python3 -m manage migrate &&
             ./scripts/wait-for-postgres.sh &&
             python3 -m manage runserver"
    volumes:
      - .:/tagged_images_manager_service
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - ENVIRONMENT=local
      - POSTGRES_DB=tagged_images_manager_service_local_db
      - POSTGRES_HOST=db

  db:
    container_name: tagged_images_manager_service_local_db_container
    build:
      context: .
      dockerfile: Dockerfile_postgresql
    image: tagged_images_manager_service_local_postgresql
    environment:
      - POSTGRES_DB=tagged_images_manager_service_local_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    volumes:
      - ./scripts/init_local_db.sh:/docker-entrypoint-initdb.d/init_local_db.sh
      - local-app-db-data:/var/lib/postgresql

volumes:
  local-app-db-data:
