version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/tagged_images_manager_service
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:14  # https://hub.docker.com/_/postgres
    environment:
      POSTGRES_DB: 'test_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./init_test_db.sql:/docker-entrypoint-initdb.d/init_test_db.sql
      - app-db-data:/var/lib/postgresql

volumes:
  app-db-data:
