from .image import ImagesViewsTestCase, ImageDetailsViewsTestCase
from .tag import TagsViewsTestCase, TagDetailsViewsTestCase
from .tag_of_image import TagsOfImageViewsTestCase, TagOfImageDetailsViewsTestCase
